import java.sql.Date;
import java.sql.Timestamp;

public class _resource_all_fields {
    private int _id;
    private String _instance = "NULL::character varying";
    private String _firstname = "NULL::character varying";
    private String _middlename = "NULL::character varying";
    private String _surname = "NULL::character varying";
    private Date _surname_last_updated;
    private String _surname_last_updated_month_text = "NULL::character varying";
    private Integer _surname_last_updated_year;
    private String _sex = "NULL::character varying";
    private Date _dob;
    private String _dob_month_text = "NULL::character varying";
    private Integer _dob_year;
    private String _basic_education_level = "NULL::character varying";
    private String _edu_evel = "NULL::character varying";
    private Date _edu_evel_last_updated;
    private String _edu_evel_last_updated_month_text = "NULL::character varying";
    private Integer _edu_evel_last_updated_year;
    private String _profession = "NULL::character varying";
    private Date _profession_last_updated;
    private String _profession_last_updated_month_text = "NULL::character varying";
    private Integer _profession_last_updated_year;
    private String _designation = "NULL::character varying";
    private Date _designation_last_updated;
    private String _designation_last_updated_month_text = "NULL::character varying";
    private Integer _designation_last_updated_year;
    private String _hosp_designation = "NULL::character varying";
    private Date _hosp_designation_last_updated;
    private String _hosp_designation_last_updated_month_text = "NULL::character varying";
    private Integer _hosp_designation_last_updated_year;
    private Date _first_appointment;
    private String _first_appointment_month_text = "NULL::character varying";
    private Integer _first_appointment_year;
    private Date _confirmation_date;
    private String _confirmation_date_month_text = "NULL::character varying";
    private Integer _confirmation_date_year;
    private Date _last_promo;
    private String _last_promo_month_text = "NULL::character varying";
    private Integer _last_promo_year;
    private Date _last_promo_last_updated;
    private String _last_promo_last_updated_month_text = "NULL::character varying";
    private Integer _last_promo_last_updated_year;
    private String _employer = "NULL::character varying";
    private String _employment_status = "NULL::character varying";
    private Date _employment_status_last_updated;
    private String _employment_status_last_updated_month_text = "NULL::character varying";
    private Integer _employment_status_last_updated_year;
    private String _employment_terms = "NULL::character varying";
    private Date _employment_terms_last_updated;
    private String _employment_terms_last_updated_month_text = "NULL::character varying";
    private Integer _employment_terms_last_updated_year;
    private String _employmentduration = "NULL::character varying";
    private String _marital = "NULL::character varying";
    private Date _marital_last_updated;
    private String _marital_last_updated_month_text = "NULL::character varying";
    private Integer _marital_last_updated_year;
    private String _check_no = "NULL::character varying";
    private String _file_no = "NULL::character varying";
    private String _department = "NULL::character varying";
    private Date _department_last_updated;
    private String _department_last_updated_month_text = "NULL::character varying";
    private Integer _department_last_updated_year;
    private String _hosp_dept = "NULL::character varying";
    private String _superlative = "NULL::character varying";
    private Date _superlative_last_updated;
    private String _superlative_last_updated_month_text = "NULL::character varying";
    private Integer _superlative_last_updated_year;
    private String _hosp_superlative_post = "NULL::character varying";
    private String _salary_scale = "NULL::character varying";
    private Date _salary_scale_last_updated;
    private String _salary_scale_last_updated_month_text = "NULL::character varying";
    private Integer _salary_scale_last_updated_year;
    private String _hosp_salary_scale = "NULL::character varying";
    private Double _salary;
    private Date _salary_last_updated;
    private String _salary_last_updated_month_text = "NULL::character varying";
    private Integer _salary_last_updated_year;
    private String _domicile = "NULL::character varying";
    private String _contact = "NULL::character varying";
    private String _contact_of_next_of_kin = "NULL::character varying";
    private String _relation_next_kin = "NULL::character varying";
    private String _disability = "NULL::character varying";
    private String _nationality = "NULL::character varying";
    private String _next_kin = "NULL::character varying";
    private Integer _number_of_children;
    private String _reg_no = "NULL::character varying";
    private String _agedistribution = "NULL::character varying";
    private Date _agedistribution_last_updated;
    private String _agedistribution_last_updated_month_text = "NULL::character varying";
    private Integer _agedistribution_last_updated_year;
    private Integer _age;
    private Integer _retirementdistribution;
    private Date _retirementdistribution_last_updated;
    private String _retirementdistribution_last_updated_month_text = "NULL::character varying";
    private Integer _retirementdistribution_last_updated_year;
    private Integer _employmentdistribution;
    private Date _employmentdistribution_last_updated;
    private String _employmentdistribution_last_updated_month_text = "NULL::character varying";
    private Integer _employmentdistribution_last_updated_year;
    private String _email = "NULL::character varying";
    private String _religion = "NULL::character varying";
    private Date _religion_last_updated;
    private String _religion_last_updated_month_text = "NULL::character varying";
    private Integer _religion_last_updated_year;
    private Date _retirementdate;
    private String _retirementdate_month_text = "NULL::character varying";
    private Integer _retirementdate_year;
    private String _level1_mohcdgec = "NULL::character varying";
    private String _level2_categories = "NULL::character varying";
    private String _level3_regions_departments_institutions_referrals = "NULL::character varying";
    private String _level4_districts_reg_hospitals = "NULL::character varying";
    private String _level5_facility = "NULL::character varying";
    private String _type = "NULL::character varying";
    private String _ownership = "NULL::character varying";
    private String _organisationunit_name = "NULL::character varying";
    private Integer _level;
    private String _levelname = "NULL::character varying";
    private String _form_name = "NULL::character varying";
    private Integer _organisationunit_id;
    private Integer _form_id;
    private Timestamp _lastupdated;
}